drop profile C##BA_USER;
CREATE PROFILE C##BA_USER LIMIT
FAILED_LOGIN_ATTEMPTS            6
PASSWORD_LIFE_TIME               UNLIMITED
PASSWORD_REUSE_TIME              720
PASSWORD_REUSE_MAX               6
PASSWORD_VERIFY_FUNCTION         PW_VERIFY_BA_USER
PASSWORD_LOCK_TIME               UNLIMITED
PASSWORD_GRACE_TIME              0;

drop profile C##BA_READONLY;
CREATE PROFILE C##BA_READONLY LIMIT
FAILED_LOGIN_ATTEMPTS 		6
PASSWORD_LIFE_TIME 		360
PASSWORD_REUSE_TIME 		720
PASSWORD_REUSE_MAX 		6
PASSWORD_VERIFY_FUNCTION 	PW_VERIFY_BA_USER
PASSWORD_LOCK_TIME 		UNLIMITED
PASSWORD_GRACE_TIME 		7;
